version: '3'

services:
  web:
    build:
      context: ./docker
      dockerfile: dockerfile.dev
    container_name: web
    command: ["aleph", "dev"]
    ports:
      - "8080:8080"
    volumes:
      - .:/code
      - aleph:/code/.aleph
      - deno_bin:$HOME/.deno/bin
      - deno_cache:$HOME/.cache/deno

volumes:
  aleph:
  deno_bin:
  deno_cache:
