version: '3'

services:
  web:
    build:
      context: ./docker
      dockerfile: dockerfile.dev
    container_name: web
    command: ["aleph", "dev"]
    ports:
      - "8080:8080"
    volumes:
      - .:/code

  static:
    build:
      context: ./docker
      dockerfile: dockerfile.nginx.dev
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
